<?php

/**
 * ProcessWire XML Parser
 *
 * ProcessWire 2.x
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * @author Tabea David <td@justonestep.de>
 * @version 0.0.1
 * @copyright Copyright (c) 2015
 * @see https://github.com/justonestep/processwire-importpagesxml
 * @see http://www.processwire.com
 */

require_once(wire('config')->paths->ImportPagesXml . 'lib/Parser.php');
require_once(wire('config')->paths->ImportPagesXml . 'lib/View.php');
use Jos\Lib\Parser;
use Jos\Lib\View;

/**
 * Class ImportPagesXml
 */
class ImportPagesXml extends Process implements Module  {

  /**
   * Module name
   *
   */
  const MODULE_NAME = 'ImportPagesXml';

  /**
   * Permission name
   *
   */
  const PERMISSION = 'page-import-xml';

  /**
   * Name used for the page created in the admin
   *
   */
  const ADMIN_PAGE_NAME = 'import-pages-xml';

  /**
   * Retrieves module meta data
   * Implementation of the Module interface
   *
   * @return array
   * @see http://processwire.com/apigen/class-Module.html
   */
  static public function getModuleInfo() {
    return array(
      'title' => 'XML Parser',
      'version' => 001,
      'summary' => 'Import XML files to create ProcessWire pages.',
      'author' => 'Tabea David',
      'icon' => 'th-list',
      'href' => 'https://github.com/justonestep/processwire-importpagesxml',
      'permission' => 'page-import-xml',
      'permissions' => array(
        'page-import-xml' => 'Administer XML Parser'
      ),
      'singular' => true,
      'autoload' => false,
    );
  }

 /**
  * construct
  */
  public function __construct() {
    $this->parser = new Parser;
    $this->view = new View;
  }

  /**
   * Initialize the module
   *
   */
  public function init() {
    parent::init();
    $page = $this->getInstalledPage();
    if ($this->page->id === $p->id) {
      if ($this->permissions->get(self::PERMISSION)->id && !$this->user->hasPermission(self::PERMISSION)) {
        throw new WirePermissionException('You have no permission to use this module');
      }
    }
  }

  /**
   * Display XML Parser Settings
   * This function is executed when a page with this Process assigned is accessed.
   */
  public function execute() {
    $action = $this->input->get->action;

    // first usage OR action `edit-preconf`
    if (!$this->parser->isPreconfigured() || $action === 'edit-preconf') {
      $output .= $this->view->renderPreconfigurationForm();
      return $output; // break, do not render additional output
    }

    // submit action `edit-preconf`
    if ($this->input->post->preconfigSubmit) {
      $this->parser->setPreconfiguration();
      $this->view->setData();
    }

    // action `edit-conf`
    if ($action === 'edit-conf') $output .= $this->view->renderMappingForm();

    // submit action `edit-conf`
    if ($this->input->post->mappingSubmit) {
      $this->parser->setConfiguration();
      $this->view->setData();
    }

    // view
    if (!$action) {
      $output .= $this->view->render();
      $form = $this->view->renderUploadForm();
      $output .= $this->view->renderUploadedFile();
      $output .= $form->render();

      // submit upload xml file
      if ($this->input->post->uploadSubmit) {
        $this->parser->setXmlFile($form);
      }
    }

    // action `parse`
    if ($action === 'parse') {
      $count = $this->parser->parse();
      if ($count['deleted']) $this->message(sprintf(__("Deleted %d pages."), $count['deleted']));
      $this->message(sprintf(__("Created %d pages."), $count['created']));
      if ($count['updated'])$this->message(sprintf(__("Updated %d pages."), $count['updated']));
      wire('session')->redirect($this->page->url);
    }

    return $output;
  }

  /**
   * Install routine
   * A new page with this Process module assigned is created.
   */
  public function ___install() {
    // create XML Parser Admin page
    $page = $this->getInstalledPage();
    $this->message("Installed to {$page->path}");
    if ($page->parent->name == 'setup') $this->message("Click to your 'Setup' page to start using the XML Importer");

    // create permission to limit access to the module
    $permission = $this->permissions->get(self::PERMISSION);
    if (!$permission->id) {
      $permission = new Permission();
      $permission->name = self::PERMISSION;
      $permission->title = $this->_('Edit XML Parser');
      $permission->save();

      $this->message('Created new permission: ' . self::PERMISSION);
    }
  }

  /**
  * Return the page that this Process is installed on
  *
  */
  protected function getInstalledPage() {
    $admin = $this->pages->get($this->config->adminRootPageID);
    $parent = $admin->child('name=setup');
    if (!$parent->id) $parent = $admin;
    $page = $parent->child('name=' . self::ADMIN_PAGE_NAME);

    if (!$page->id) {
      $page = new Page();
      $page->parent = $parent;
      $page->template = $this->templates->get('admin');
      $page->name = self::ADMIN_PAGE_NAME;
      $page->title = "Import Pages From XML";
      $page->process = $this;
      $page->sort = $parent->numChildren;
      $page->save();
    }

    return $page;
  }

  /**
   * Uninstall routine
   *
   * This should return the site to the same state
   * it was in before the module was installed.
   */
  public function ___uninstall() {
    // delete the admin page
    $page = $this->getInstalledPage();

    if ($page->id) {
      $page->delete();
      $this->message("Deleted Page: {$page->path}");
    }

    // delete the permission
    $permission = $this->permissions->get(self::PERMISSION);
    if ($permission->id) {
      $permission->delete();
      $this->message("Deleted Permission: " . self::PERMISSION);
    }
  }
}
