<?php

/**
 * ProcessWire XML Parser
 *
 * ProcessWire 2.x
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * @author Tabea David <td@justonestep.de>
 * @version 0.0.1
 * @copyright Copyright (c) 2015 
 * @see https://github.com/justonestep/processwire-xmlparser
 * @see http://www.processwire.com
 */

require_once(wire('config')->paths->XmlParser . 'lib/Parser.php');
use Jos\Parser;

/**
 * Class XmlParser
 */
class XmlParser extends Process implements Module  {

  const PAGE_NAME = 'XML Parser';
  const MODULE_NAME = 'XmlParser';
  const PERMISSION = 'xmlparser';

  /**
   * Retrieves module meta data
   * Implementation of the Module interface
   *
   * @return array
   * @see http://processwire.com/apigen/class-Module.html
   */
  static public function getModuleInfo() {
    return array(
      'title' => 'XML Parser',
      'version' => 001,
      'summary' => '',
      'author' => 'Tabea David',
      'icon' => 'th-list',
      'href' => 'https://github.com/justonestep/processwire-xmlparser',
      'useNavJSON' => true,
      'permission' => 'xmlparser',
      'permissions' => array(
        'xmlparser' => 'Administer XML Parser'
      ),
      'singular' => false,
      'autoload' => true,
    );
  }

  /**
   * @field array Default config values
   */
  protected static $defaults = array(
    'xpTmplate' => '',
    'xpParent' => ''
  );

 /**
  * construct
  */
  public function __construct() {
    $this->parser = new Parser;
  }

  /**
   * Initialize the module
   *
   */
  public function init() {
    if ($this->permissions->get(self::PERMISSION)->id && !$this->user->hasPermission(self::PERMISSION)) {
      throw new WirePermissionException('You have no permission to use this module');
    }
  }

  /**
   * Display XML Parser Settings
   * This function is executed when a page with this Process assigned is accessed.
   */
  public function execute() {
    $output = '';

    $isPreconf = !$this->parser->isPreconfigured() && !$this->parser->isPreconfigurationRunning();
    if ($isPreconf || $this->input->get->action === 'edit') {
      $output .= $this->renderPreconfigurationForm();
    } else if ($this->parser->isPreconfigurationRunning()) {
      $this->parser->setPreconfiguration();
    }

    $output .= $this->renderPreconfigurationView();
    $output .= $this->renderMappingForm();

    return $output;
  }

  private function renderMappingForm() {
    $template = $this->templates->get($this->parser->data['xpTemplate']);

    $form = $this->modules->get('InputfieldForm');
    $form->attr('id', 'xmlparser');
    $form->action = './';
    $form->method = 'post';

    $wrapper = new InputfieldWrapper();
    $wrapper->attr('title', $this->_('Mapping'));

    $set = $this->modules->get('InputfieldFieldset');
    $set->label = $this->_('Mapping');

    foreach ($template->fields as $tfield) {
      // @todo: implement repeater handling
      $field = $this->modules->get('InputfieldText');
      $field->label = $tfield->name;
      $field->name = $tfield->name;
      $field->size = 30;
      $field->attr('value', $this->parser->data['']); // @todo
      $field->columnWidth = 50;

      $set->add($field);
    }

    $wrapper->add($set);
    $form->add($wrapper);

    $this->addSubmit($form);

    return $form->render();
  }

  private function renderPreconfigurationView() {
    $edit = $this->page->url . '?action=edit';
    $output = '<h2>' . $this->_('Presets') . '</h2>';
    $output .= '<dl class="nav">';

    foreach ($this->parser->getPreconfiguration() as $config) {
      $output .= "<dt><a class='label' href='$edit'>{$config['name']}</a></dt>";
      $output .= "<dd><div class='actions'>{$config['val']} <a href='$edit'>{$this->_('Edit')}</a></div></dd>";
    }
    $output .= '</dl>';

    return $output;
  }

  private function renderPreconfigurationForm() {
    $form = $this->modules->get('InputfieldForm');
    $form->attr('id', 'xmlparser');
    $form->action = './';
    $form->method = 'post';

    $wrapper = new InputfieldWrapper();
    $wrapper->attr('title', $this->_('Overview'));

    $set = $this->modules->get('InputfieldFieldset');
    $set->label = $this->_('Settings');

    $fieldTemplate = $this->modules->get('InputfieldSelect');
    $fieldTemplate->label = $this->_('Template');
    $fieldTemplate->attr('name', 'xpTemplate');
    $fieldTemplate->attr('value', $this->parser->data['xpTemplate']);
    $fieldTemplate->required = true;
    $fieldTemplate->columnWidth = 50;
    $fieldTemplate->addOption('', '');
    foreach ($this->templates as $template) {
      if ($template->flags & \Template::flagSystem) continue;
      $fieldTemplate->addOption($template->id, (!empty($template->label) ? $template->label : $template->name));
    }

    $fieldPage = $this->modules->get('InputfieldPageListSelect');
    $fieldPage->label = $this->_('Parent Page');
    $fieldPage->name = 'xpParent';
    $fieldPage->required = true;
    $fieldPage->attr('value', $this->parser->data['xpParent']);
    $fieldPage->columnWidth = 50;

    $set->add($fieldTemplate);
    $set->add($fieldPage);

    $wrapper->add($set);
    $form->add($wrapper);

    $this->addSubmit($form);

    return $form->render();
  }

  /**
   * Add a submit button, moved to a function so we don't have to do this several times
   *
   */
  protected function addSubmit(InputfieldForm $form) {
    $f = $this->modules->get('InputfieldSubmit');
    $f->name = 'submit';
    $f->value = $this->_('Submit');
    $form->add($f);
  }

  /**
   * Install routine
   * A new page with this Process module assigned is created.
   */
  public function ___install() {
    // create XML Parser Admin page
    $page = $this->pages->get('template=admin, name=' . self::PAGE_NAME);
    if (!$page->id) {
      $page = new Page();
      $page->template = 'admin';
      $page->parent = $this->pages->get($this->config->adminRootPageID);
      $page->title = self::PAGE_NAME;
      $page->name = self::PAGE_NAME;
      $page->process = $this;
      $page->save();

      $this->message("Created Page: {$page->path}");
    }

    // create permission to limit access to the module
    $permission = $this->permissions->get(self::PERMISSION);
    if (!$permission->id) {
      $permission = new Permission();
      $permission->name = self::PERMISSION;
      $permission->title = $this->_('Edit XML Parser');
      $permission->save();

      $this->message('Created new permission: ' . self::PERMISSION);
    }
  }

  /**
   * Uninstall routine
   * 
   * This should return the site to the same state 
   * it was in before the module was installed. 
   */
  public function ___uninstall() {
    // delete the admin page
    $moduleID = $this->modules->getModuleID($this); 
    $selector = "template=admin, process=$moduleID, name=" . self::PAGE_NAME;
    $page = $this->pages->get($selector); 

    if ($page->id) {
      $page->delete();
      $this->message("Deleted Page: {$page->path}"); 
    }

    // delete the xmlparser permission
    $permission = $this->permissions->get(self::PERMISSION);
    if ($permission->id) {
      $permission->delete();
      $this->message("Deleted Permission: " . self::PERMISSION);
    }
  }
}
